server:
  port: 8080
spring:
  application:
    name: wydp
  #DataSource Config
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wydp?serverTimezone=UTC
    username: root
    password: gao20011208
  #Redis Config
  redis:
    host: 192.168.88.161
    port: 6379
    password: 123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s

  #session
  session:
    timeout: 64000
    store-type: redis
logging:
  level:
    org.springframework.boot.autoconfigure: error
